/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health/live": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness */
    get: operations["liveness_health_live_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Readiness */
    get: operations["readiness_health_ready_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Me */
    get: operations["get_me_v1_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/tenants/{tenant_id}/audit-events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Audit Events */
    get: operations["list_audit_events_v1_tenants__tenant_id__audit_events_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/tenants/{tenant_id}/batches/{batch_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Batch */
    get: operations["get_batch_v1_tenants__tenant_id__batches__batch_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/tenants/{tenant_id}/batches/{batch_id}/rows": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Batch Rows */
    get: operations["list_batch_rows_v1_tenants__tenant_id__batches__batch_id__rows_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/tenants/{tenant_id}/datasets": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Dataset */
    post: operations["create_dataset_v1_tenants__tenant_id__datasets_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/tenants/{tenant_id}/decisions/{decision_id}/approve": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Approve Decision */
    post: operations["approve_decision_v1_tenants__tenant_id__decisions__decision_id__approve_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/tenants/{tenant_id}/decisions/{decision_id}/reverse": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reverse Decision */
    post: operations["reverse_decision_v1_tenants__tenant_id__decisions__decision_id__reverse_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/tenants/{tenant_id}/mappings/{mapping_id}/approve": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Approve Mapping */
    post: operations["approve_mapping_v1_tenants__tenant_id__mappings__mapping_id__approve_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/tenants/{tenant_id}/mappings/{mapping_id}/preview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Preview Mapping */
    post: operations["preview_mapping_v1_tenants__tenant_id__mappings__mapping_id__preview_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/tenants/{tenant_id}/runs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Run */
    post: operations["create_run_v1_tenants__tenant_id__runs_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/tenants/{tenant_id}/runs/{run_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Run */
    get: operations["get_run_v1_tenants__tenant_id__runs__run_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/tenants/{tenant_id}/runs/{run_id}/cancel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Cancel Run */
    post: operations["cancel_run_v1_tenants__tenant_id__runs__run_id__cancel_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/tenants/{tenant_id}/runs/{run_id}/decisions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Propose Decision */
    post: operations["propose_decision_v1_tenants__tenant_id__runs__run_id__decisions_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/tenants/{tenant_id}/runs/{run_id}/exceptions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Exceptions */
    get: operations["list_exceptions_v1_tenants__tenant_id__runs__run_id__exceptions_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/tenants/{tenant_id}/runs/{run_id}/matches": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Matches */
    get: operations["list_matches_v1_tenants__tenant_id__runs__run_id__matches_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/tenants/{tenant_id}/runs/{run_id}/summary": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Run Summary */
    get: operations["get_run_summary_v1_tenants__tenant_id__runs__run_id__summary_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/tenants/{tenant_id}/sources": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Source */
    post: operations["create_source_v1_tenants__tenant_id__sources_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/tenants/{tenant_id}/sources/{source_id}/mappings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Mapping */
    post: operations["create_mapping_v1_tenants__tenant_id__sources__source_id__mappings_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/tenants/{tenant_id}/sources/{source_id}/uploads": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reserve Upload */
    post: operations["reserve_upload_v1_tenants__tenant_id__sources__source_id__uploads_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/tenants/{tenant_id}/uploads/{upload_id}/complete": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Complete Upload */
    post: operations["complete_upload_v1_tenants__tenant_id__uploads__upload_id__complete_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/tenants/{tenant_id}/workflow-revisions/{revision_id}/approve": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Approve Workflow Revision */
    post: operations["approve_workflow_revision_v1_tenants__tenant_id__workflow_revisions__revision_id__approve_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/tenants/{tenant_id}/workflow-revisions/{revision_id}/preview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Preview Workflow Revision */
    post: operations["preview_workflow_revision_v1_tenants__tenant_id__workflow_revisions__revision_id__preview_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/tenants/{tenant_id}/workflows": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Workflow */
    post: operations["create_workflow_v1_tenants__tenant_id__workflows_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/tenants/{tenant_id}/workflows/{workflow_id}/revisions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Workflow Revision */
    post: operations["create_workflow_revision_v1_tenants__tenant_id__workflows__workflow_id__revisions_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ApproveDecisionRequest */
    ApproveDecisionRequest: {
      /** Expected Version */
      expected_version: number;
    };
    /** ApproveMappingRequest */
    ApproveMappingRequest: {
      /** Expected Version */
      expected_version: number;
      /** Preview Sha256 */
      preview_sha256: string;
    };
    /** ApproveWorkflowRequest */
    ApproveWorkflowRequest: {
      /** Expected Version */
      expected_version: number;
      /** Preview Sha256 */
      preview_sha256: string;
    };
    /** AuditEventResponse */
    AuditEventResponse: {
      /** Actor */
      actor: string;
      /** Event Type */
      event_type: string;
      /** Id */
      id: string;
      /** Metadata */
      metadata: {
        [key: string]: unknown;
      };
      /** Request Id */
      request_id: string;
      /** Resource Id */
      resource_id: string;
      /** Resource Type */
      resource_type: string;
      /** Sequence */
      sequence: number;
    };
    /** BatchResponse */
    BatchResponse: {
      /** Accepted Rows */
      accepted_rows: number | null;
      /** Excluded Rows */
      excluded_rows: number | null;
      /** Id */
      id: string;
      /** Invalid Rows */
      invalid_rows: number | null;
      /** Issues */
      issues: {
        [key: string]: unknown;
      }[];
      /** Physical Rows */
      physical_rows: number | null;
      /** Source Id */
      source_id: string;
      /** State */
      state: string;
    };
    /** Body_complete_upload_v1_tenants__tenant_id__uploads__upload_id__complete_post */
    Body_complete_upload_v1_tenants__tenant_id__uploads__upload_id__complete_post: {
      /** File */
      file: string;
    };
    /** CompleteUploadResponse */
    CompleteUploadResponse: {
      /** Accepted Rows */
      accepted_rows: number | null;
      /** Already Completed */
      already_completed: boolean;
      /** Batch Id */
      batch_id: string;
      /** Excluded Rows */
      excluded_rows: number | null;
      /** Invalid Rows */
      invalid_rows: number | null;
      /** Physical Rows */
      physical_rows: number | null;
      /** State */
      state: string;
    };
    /** CreateDatasetRequest */
    CreateDatasetRequest: {
      /** Batch Id */
      batch_id: string;
      /** Mapping Id */
      mapping_id: string;
    };
    /** CreateMappingRequest */
    CreateMappingRequest: {
      /** Definition */
      definition: {
        [key: string]: unknown;
      };
      /** Source Id */
      source_id: string;
    };
    /** CreateRevisionRequest */
    CreateRevisionRequest: {
      /** Definition */
      definition: {
        [key: string]: unknown;
      };
    };
    /** CreateRunRequest */
    CreateRunRequest: {
      /** Dataset A Id */
      dataset_a_id: string;
      /** Dataset B Id */
      dataset_b_id: string;
      /** Mode */
      mode: string;
      /** Workflow Revision Id */
      workflow_revision_id: string;
    };
    /** CreateSourceRequest */
    CreateSourceRequest: {
      /** Kind */
      kind: string;
      /** Name */
      name: string;
    };
    /** CreateWorkflowRequest */
    CreateWorkflowRequest: {
      /** Name */
      name: string;
    };
    /** CurrencySummaryResponse */
    CurrencySummaryResponse: {
      /** Amount A */
      amount_a: string;
      /** Amount B */
      amount_b: string;
      /** Currency */
      currency: string;
      /** Group Count */
      group_count: number;
      /** Record Count A */
      record_count_a: number;
      /** Record Count B */
      record_count_b: number;
    };
    /** DatasetResponse */
    DatasetResponse: {
      /** Id */
      id: string;
    };
    /** DecisionApprovalResponse */
    DecisionApprovalResponse: {
      /** Action */
      action: string;
      /** Group Id */
      group_id: string;
      /** Id */
      id: string;
    };
    /** DecisionResponse */
    DecisionResponse: {
      /** Id */
      id: string;
      /**
       * State
       * @default proposed
       */
      state: string;
    };
    /** ExceptionCaseResponse */
    ExceptionCaseResponse: {
      /** Assigned To */
      assigned_to: string | null;
      /** Id */
      id: string;
      /** Reason Code */
      reason_code: string;
      /** Related Record Ids */
      related_record_ids: string[];
      /** Severity */
      severity: string;
      /** State */
      state: string;
      /** Version */
      version: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** LivenessResponse */
    LivenessResponse: {
      /**
       * Status
       * @default ok
       */
      status: string;
    };
    /** MappingResponse */
    MappingResponse: {
      /** Id */
      id: string;
    };
    /** MatchGroupResponse */
    MatchGroupResponse: {
      /** Amount A */
      amount_a: string;
      /** Amount B */
      amount_b: string;
      /** Currency */
      currency: string;
      /** Difference */
      difference: string;
      /** Evidence */
      evidence: {
        [key: string]: unknown;
      };
      /** Id */
      id: string;
      /** Kind */
      kind: string;
      /** Rule Id */
      rule_id: string;
      /** State */
      state: string;
    };
    /** MeResponse */
    MeResponse: {
      /** Issuer */
      issuer: string;
      /** Subject */
      subject: string;
      /** Tenants */
      tenants: components["schemas"]["MembershipView"][];
    };
    /** MembershipView */
    MembershipView: {
      /** Roles */
      roles: string[];
      /** Tenant Id */
      tenant_id: string;
    };
    /** PreviewResponse */
    PreviewResponse: {
      /** Control Totals */
      control_totals: {
        [key: string]: string | number;
      }[];
      /** Expected Version */
      expected_version: number;
      /** Invalid Rows */
      invalid_rows: number;
      /** Preview Sha256 */
      preview_sha256: string;
      /** Valid Rows */
      valid_rows: number;
    };
    /** PreviewWorkflowRequest */
    PreviewWorkflowRequest: {
      /** Dataset A Id */
      dataset_a_id: string;
      /** Dataset B Id */
      dataset_b_id: string;
    };
    /** ProposeDecisionRequest */
    ProposeDecisionRequest: {
      /** Action */
      action: string;
      /** Expected Version */
      expected_version: number;
      /** Group Id */
      group_id: string;
      /** Reason */
      reason: string;
    };
    /** ReadinessResponse */
    ReadinessResponse: {
      /** Database */
      database: string;
      /** Status */
      status: string;
    };
    /** ReserveUploadRequest */
    ReserveUploadRequest: {
      /** Declared Bytes */
      declared_bytes: number;
      /** Filename */
      filename: string;
      /** Sha256 */
      sha256: string;
    };
    /** ReserveUploadResponse */
    ReserveUploadResponse: {
      /** Expires At */
      expires_at: string;
      /** Upload Id */
      upload_id: string;
    };
    /** ReverseDecisionRequest */
    ReverseDecisionRequest: {
      /** Reason */
      reason: string;
    };
    /** RevisionResponse */
    RevisionResponse: {
      /** Id */
      id: string;
    };
    /** RowPageResponse */
    RowPageResponse: {
      /** Next After Ordinal */
      next_after_ordinal: number | null;
      /** Rows */
      rows: components["schemas"]["RowResponse"][];
    };
    /** RowResponse */
    RowResponse: {
      /** Cells */
      cells: {
        [key: string]: string;
      };
      /** Id */
      id: string;
      /** Ordinal */
      ordinal: number;
    };
    /** RunResponse */
    RunResponse: {
      /** Id */
      id: string;
    };
    /** RunStatusResponse */
    RunStatusResponse: {
      /** Cancel Requested */
      cancel_requested: boolean;
      /** Id */
      id: string;
      /** Mode */
      mode: string;
      /** Published Attempt Id */
      published_attempt_id: string | null;
      /** State */
      state: string;
      /** Version */
      version: number;
    };
    /** SourceResponse */
    SourceResponse: {
      /** Id */
      id: string;
      /** Kind */
      kind: string;
      /** Name */
      name: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** WorkflowPreviewResponse */
    WorkflowPreviewResponse: {
      /** Expected Version */
      expected_version: number;
      /** Preview Sha256 */
      preview_sha256: string;
      /** Proposed Groups */
      proposed_groups: number;
      /** Residuals */
      residuals: number;
    };
    /** WorkflowResponse */
    WorkflowResponse: {
      /** Id */
      id: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  liveness_health_live_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LivenessResponse"];
        };
      };
    };
  };
  readiness_health_ready_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReadinessResponse"];
        };
      };
    };
  };
  get_me_v1_me_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_audit_events_v1_tenants__tenant_id__audit_events_get: {
    parameters: {
      query?: {
        resource_id?: string | null;
        after_sequence?: number;
        limit?: number;
      };
      header?: {
        authorization?: string | null;
      };
      path: {
        tenant_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuditEventResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_batch_v1_tenants__tenant_id__batches__batch_id__get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        batch_id: string;
        tenant_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BatchResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_batch_rows_v1_tenants__tenant_id__batches__batch_id__rows_get: {
    parameters: {
      query?: {
        after_ordinal?: number;
        limit?: number;
      };
      header?: {
        authorization?: string | null;
      };
      path: {
        batch_id: string;
        tenant_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RowPageResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_dataset_v1_tenants__tenant_id__datasets_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        tenant_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateDatasetRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DatasetResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  approve_decision_v1_tenants__tenant_id__decisions__decision_id__approve_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        decision_id: string;
        tenant_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ApproveDecisionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DecisionApprovalResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  reverse_decision_v1_tenants__tenant_id__decisions__decision_id__reverse_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        decision_id: string;
        tenant_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReverseDecisionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DecisionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  approve_mapping_v1_tenants__tenant_id__mappings__mapping_id__approve_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        mapping_id: string;
        tenant_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ApproveMappingRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  preview_mapping_v1_tenants__tenant_id__mappings__mapping_id__preview_post: {
    parameters: {
      query: {
        batch_id: string;
      };
      header?: {
        authorization?: string | null;
      };
      path: {
        mapping_id: string;
        tenant_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PreviewResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_run_v1_tenants__tenant_id__runs_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        tenant_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateRunRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_run_v1_tenants__tenant_id__runs__run_id__get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        run_id: string;
        tenant_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunStatusResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  cancel_run_v1_tenants__tenant_id__runs__run_id__cancel_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        run_id: string;
        tenant_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  propose_decision_v1_tenants__tenant_id__runs__run_id__decisions_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        run_id: string;
        tenant_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProposeDecisionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DecisionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_exceptions_v1_tenants__tenant_id__runs__run_id__exceptions_get: {
    parameters: {
      query?: {
        after_id?: string | null;
        limit?: number;
      };
      header?: {
        authorization?: string | null;
      };
      path: {
        run_id: string;
        tenant_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExceptionCaseResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_matches_v1_tenants__tenant_id__runs__run_id__matches_get: {
    parameters: {
      query?: {
        after_id?: string | null;
        limit?: number;
      };
      header?: {
        authorization?: string | null;
      };
      path: {
        run_id: string;
        tenant_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MatchGroupResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_run_summary_v1_tenants__tenant_id__runs__run_id__summary_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        run_id: string;
        tenant_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CurrencySummaryResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_source_v1_tenants__tenant_id__sources_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        tenant_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateSourceRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SourceResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_mapping_v1_tenants__tenant_id__sources__source_id__mappings_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        source_id: string;
        tenant_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateMappingRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MappingResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  reserve_upload_v1_tenants__tenant_id__sources__source_id__uploads_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        source_id: string;
        tenant_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReserveUploadRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReserveUploadResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  complete_upload_v1_tenants__tenant_id__uploads__upload_id__complete_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        upload_id: string;
        tenant_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_complete_upload_v1_tenants__tenant_id__uploads__upload_id__complete_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CompleteUploadResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  approve_workflow_revision_v1_tenants__tenant_id__workflow_revisions__revision_id__approve_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        revision_id: string;
        tenant_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ApproveWorkflowRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  preview_workflow_revision_v1_tenants__tenant_id__workflow_revisions__revision_id__preview_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        revision_id: string;
        tenant_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PreviewWorkflowRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkflowPreviewResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_workflow_v1_tenants__tenant_id__workflows_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        tenant_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateWorkflowRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkflowResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_workflow_revision_v1_tenants__tenant_id__workflows__workflow_id__revisions_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        workflow_id: string;
        tenant_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateRevisionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RevisionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
